### PR TITLE
circleci 2

### PR DESCRIPTION
**Pull request by jandegr**
porting QA to circle 2.0

apparently anything after commit af9ec70 (May 19, 2019) in the navit-gps/navit repo breaks something.
see comments I left in config.yml
@pgrandin : any clue ??

for the rest a minor issue regarding the size of the png's and the testing itself to be finalized.

### CODE REVIEW

**Comment by pgrandin** [comment]
I ran a git bisect and it looks like https://github.com/navit-gps/navit/commit/b2205d39d2864f4ed7fd3d931b2e6b8f06a6b38b is what's breaking the commit. I'll dig.

**Comment by jandegr** [comment]
Hi,
b2205d3 works too, see https://circleci.com/gh/jandegr/routing-qa/578
and it is one day younger than  af9ec70 so I edited the comments in config.yml accordingly.
I seem to have missed that one.

The first problem is it does not find the plugins, so I tested it with -DUSE_PLUGINS=n
then it does not crash but does not find xml's and the map.
https://circleci.com/gh/jandegr/routing-qa/577

I tested it locally with an absolute path specified for the map in navit.xml, then it renders the map but does not find the icons for gui_internal.

IIRC correctly, running it from within the builddir has always worked in the past and it is how QA and other testing was done on CI and while I was working on it locally I always ran it that way too.

thx for the help, despite this repo (QA) being the least visited section of navit, I think it was the most interesting one, let's hope it can work again some day :)

**Comment by jandegr** [comment]
got it, a little slow but still :)

https://github.com/navit-gps/navit/commit/bbff86825991abb7408abf1691118b112c83bed2
removes version.h

but then 
https://github.com/navit-gps/navit/blob/trunk/navit/main.c#L353
does not work for us anymore

as a temporary workarount we just touch version.h

maybe @bignaux can propose a solution in the navit-gps/navit repo ?

Next is the size of the png's to fix I suppose.

thx.

**Comment by jandegr** [comment]
Tested with a tweak to look for `Makefile` instead of `version.h`, 
https://circleci.com/gh/jandegr/routing-qa/582#artifacts/containers/0

relates to https://github.com/navit-gps/navit/pull/803

**Comment by jandegr** [comment]
Demovehicle reported as broken by gernot2 on IRC and confirmed here https://circleci.com/gh/jandegr/routing-qa/587
The route is found but never updated because demovehicle just does not move, maybe out of fuel ?

**Comment by jandegr** [comment]
Closing for now, I can open a new PR if Navit gets fixed

**Pull request closed without merging**
